export let Country = {
    Austria: "austria",
    Bulgaria: "bulgaria",
    Croatia: "croatia",
    Czech: "czech",
    France: "france",
    Germany: "germany",
    Greece: "greece",
    Hungary: "hungary",
    Italy: "italy",
    Montenegro: "montenegro",
    NorthMacedonia: "north-macedonia",
    Poland: "poland",
    Romania: "romania",
    Serbia: "serbia",
    Slovakia: "slovakia",
    Slovenia: "slovenia",
    Spain: "spain",
    Switzerland: "switzerland",
}

export let allCountries = [
    Country.Austria,
    Country.Bulgaria,
    Country.Croatia,
    Country.Czech,
    Country.France,
    Country.Germany,
    Country.Greece,
    Country.Hungary,
    Country.Italy,
    Country.Montenegro,
    Country.NorthMacedonia,
    Country.Poland,
    Country.Romania,
    Country.Serbia,
    Country.Slovakia,
    Country.Slovenia,
    Country.Spain,
    Country.Switzerland,
]

export let City = {
    // Austria
    Vienna: "vienna",
    Gratz: "gratz",
    Linz: "linz",
    Salzburg: "salzburg",
    Innsbruck: "innsbruck",
    KragenfurtWertez: "kragenfurt-wertez",
    SanktPeltin: "sankt-peltin",
    Bregenz: "bregenz",
    Parndorf: "parndorf",

    // Bulgaria,
    Burgas: "burgas",
    Sofia: "sofia",
    Varna: "varna",
    Plovdiv: "plovdiv",
    Pleven: "pleven",
    Ruse: "ruse",
    
    // Croatia,
    Zagreb: "zagreb",
    Split: "split",
    Rijeka: "rijeka",
    Osijek: "osijek",
    Zadar: "zadar",
    Karlovac: "karlovac",
    Pula: "pula",
    Sisak: "sisak",
    Sibenik: "sibenik",
    Varazdin: "varazdin",
    Dubrovnik: "dubrovnik",
    Belovar: "belovar",
    Porec: "porec",
    Omis: "omis",
    Makarska: "makarska",
    BaskaVoda: "baska-voda",
    Makarska: "makarska",
    Rovinj: "rovinj",

    // Czech,
    Brno: "brno",
    Prague: "prague",
    Ostrava: "ostrava",
    Plzen: "plzen",
    Liberec: "liberec",
    Olomouc: "olomouc",
    CeskeBudejovice: "ceske-budejovice",
    HradecKralove: "hradec-kralove",
    UstiNadLabem: "usti-nad-labem",
    Pardubice: "pardubice",
    Zlin: "zlin",
    Kladno: "kladno",
    Opava: "opava",
    Jihlava: "jihlava",
    Teplice: "teplice",
    Chomutov: "chomutov",
    KarlovyVary: "karlovy-vary",
    
    // France,
    Lyon: "lyon",
    Marceille: "marceille",
    Nice: "nice",
    Paris: "paris",
    Toulouse: "toulouse",

    // Germany,
    Berlin: "berlin",
    Munich: "munich",
    Nurnberg: "nurnberg",
    Gamburg: "gamburg",
    Keln: "keln",
    Frankfurt: "frankfurt",
    Dusseldorf: "dusseldorf",
    Leiptsig: "leiptsig",
    Dortmund: "dortmund",
    Essen: "essen",
    Bremen: "bremen",
    Drezden: "drezden",
    Gannover: "gannover",
    Magdeburg: "magdeburg",
    Rostok: "rostok",

    // Greece,
    Athens: "athens",
    Santorini: "santorini",
    Mykonos: "mykonos",
    Crete: "crete",
    Rhodes: "rhodes",
    Corfu: "corfu",
    Meteora: "meteora",
    Delphi: "delphi",
    Nafplion: "nafplion",
    Olympia: "olympia",
    Zakynthos: "zakynthos",
    Thessaloniki: "thessaloniki",
    Kavala: "kavala",
    Alexandroupolis: "alexandroupolis",
    Sarti: "sarti",
    
    // Hungary,
    Budapest: "budapest",
    Debretsen: "debretsen",
    Seged: "seged",
    Mishkolts: "mishkolts",
    Pech: "pech",
    Dior: "dior",
    Kaposhvar: "kaposhvar",
    Nyiredgaza: "nyiredgaza",
    Kechkemet: "kechkemet",
    Sekeshfegervar: "sekeshfegervar",
    Sombatgey: "sombatgey",
    Solnok: "solnok",
    Tatabanya: "tatabanya",
    Bekeshchaba: "bekeshchaba",
    Erd: "erd",
    Veshprem: "veshprem",
    Shopron: "shopron",
    Eger: "eger",
    
    // Italy,
    Milan: "milan",
    Roma: "roma",
    Venice: "venice",
    Bologna: "bologna",
    Rimini: "rimini",
    Ravenna: "ravenna",
    Pesaro: "pesaro",
    Ancona: "ancona",
    Pescara: "pescara",
    Bari: "bari",
    Palermo: "palermo",
    Naples: "naples",
    Siena: "siena",
    Florence: "florence",
    SanMarino: "san-marino",
    Verona: "verona",
    Genoa: "genoa",
    Parma: "parma",
    Turin: "turin",
    Livorno: "livorno",
    Lucca: "lucca",

    // Montenegro,
    Budva: "budva",
    Podgorica: "podgorica",
    Sutomore: "sutomore",
    Bar: "bar",
    DubrovnikM: "dubrovnik-m",

    // North Macedonia,
    Skopje: "skopje",
    Tetovo: "tetovo",
    Gostivar: "gostivar",
    Kichevo: "kichevo",
    Veles: "veles",
    Prilep: "prilep",
    Bitola: "bitola",
    Kumanovo: "kumanovo",
    Shtip: "shtip",
    Strumica: "strumica",
    
    // Poland,
    Krakow: "krakow",
    Warsaw: "warsaw",
    Wroclav: "wroclav",
    Lodz: "lodz",
    Poznan: "poznan",
    Gdansk: "gdansk",
    Szczecin: "szczecin",
    Bydgoszcz: "bydgoszcz",
    Lublin: "lublin",
    Katowice: "katowice",
    Gdynia: "gdynia",
    Czestochowa: "czestochowa",
    Radom: "radom",
    Sosnowiec: "sosnowiec",
    
    // Romania,
    Buharest: "buharest",

    // Serbia,
    Belgrad: "belgrad",
    NoviSad: "novisad",
    Nish: "nish",
    Subotica: "subotica",
    Kraguevac: "kraguevac",
    Kralevo: "kralevo",
    Vranje: "vranje",
    Zrenyanin: "zrenyanin",
    Vrshats: "vrsaс",
    SremskaMitrovica: "sremska-mitrovica",
    Pozarevac: "pozarevac",
    Sombor: "sombor",
    Panchievo: "panchievo",
    Leskovats: "leskovats",
    Smederevo: "smederevo",
    
    // Slovakia,
    BanskaBystrica: "banskabystrica",
    Bratislava: "bratislava",
    Humenne: "humenne",
    Koshitse: "koshitse",
    Levoca: "levoca",
    Levice: "levice",
    Malacky: "malacky",
    Martin: "martin",
    Michalovce: "michalovce",
    Nitra: "nitra",
    NoveZamky: "novezamky",
    Poprad: "poprad",
    Presov: "presov",
    Prievidza: "prievidza",
    Ruzomberok: "ruzomberok",
    Skalica: "skalica",
    Trencin: "trencin",
    Trnava: "trnava",
    Zilina: "zilina",
    Zvolen: "zvolen",
    
    // Slovenia,
    Ljublijana: "ljublijana",
    Maribor: "maribor",
    Tsele: "tsele",
    Kran: "kran",
    Velenye: "velenye",
    Koper: "koper",
    NoveMesto: "novemesto",
    Ptuy: "ptuy",   
    Trbovlje: "trbovlje",
    Jesenice: "jesenice",
    
    // Spain,
    Barcelona: "barcelona",
    Madrid: "madrid",
    Valencia: "valencia",

    // Switzerland,
    Bern: "bern",
    Zurich: "zurich",
    Geneva: "geneva",
    Basel: "basel",
    Bern: "bern",
    Lausanne: "lausanne",
    Winterthur: "winterthur",
    Lucerne: "lucerne",
    SaintGallen: "saint-gallen",
    Biel: "biel",
    Thun: "thun",
    Kenitz: "kenitz",
}

export const countriesCities = {
    [Country.Austria]: [
        City.Vienna,
        City.Gratz,
        City.Linz,
        City.Salzburg,
        City.Innsbruck,
        City.KragenfurtWertez,
        City.SanktPeltin,
        City.Bregenz,
        City.Parndorf,
    ],
    [Country.Bulgaria]: [
        City.Burgas, 
        City.Varna, 
        City.Sofia,
        City.Plovdiv,
        City.Pleven,
        City.Ruse,
    ],
    [Country.Croatia]: [
        City.Zagreb,
        City.Split,
        City.Rijeka,
        City.Osijek,
        City.Zadar,
        City.Karlovac,
        City.Pula,
        City.Sisak,
        City.Sibenik,
        City.Varazdin,
        City.Dubrovnik,
        City.Belovar,
        City.Porec,
        City.Omis,
        City.Makarska,
        City.BaskaVoda,
        City.Makarska,
        City.Rovinj,
    ],
    [Country.Czech]: [
        City.Prague, 
        City.Brno,
        City.Ostrava,
        City.Plzen,
        City.Liberec,
        City.Olomouc,
        City.CeskeBudejovice,
        City.HradecKralove,
        City.UstiNadLabem,
        City.Pardubice,
        City.Zlin,
        City.Kladno,
        City.Opava,
        City.Jihlava,
        City.Teplice,
        City.Chomutov,
        City.KarlovyVary,
    ],
    [Country.France]: [
        City.Lyon, 
        City.Nice, 
        City.Paris, 
        City.Toulouse, 
        City.Marceille,
    ],
    [Country.Germany]: [
        City.Berlin, 
        City.Munich, 
        City.Nurnberg,
        City.Gamburg,
        City.Keln,
        City.Frankfurt,
        City.Dusseldorf,
        City.Leiptsig,
        City.Dortmund,
        City.Essen,
        City.Bremen,
        City.Drezden,
        City.Gannover,
        City.Magdeburg,
        City.Rostok,
    ],
    [Country.Greece]: [
        City.Athens,
        City.Santorini,
        City.Mykonos,
        City.Crete,
        City.Rhodes,
        City.Corfu,
        City.Meteora,
        City.Delphi,
        City.Nafplion,
        City.Olympia,
        City.Zakynthos,
        City.Thessaloniki,
        City.Kavala,
        City.Alexandroupolis,
        City.Sarti,
    ],
    [Country.Hungary]: [
        City.Budapest,
        City.Debretsen,
        City.Seged,
        City.Mishkolts,
        City.Pech,
        City.Dior,
        City.Kaposhvar,
        City.Nyiredgaza,
        City.Kechkemet,
        City.Sekeshfegervar,
        City.Sombatgey,
        City.Solnok,
        City.Tatabanya,
        City.Bekeshchaba,
        City.Erd,
        City.Veshprem,
        City.Shopron,
        City.Eger,
    ], 
    [Country.Italy]: [
        City.Roma, 
        City.Milan,
        City.Venice,
        City.Bologna,
        City.Rimini,
        City.Ravenna,
        City.Pesaro,
        City.Ancona,
        City.Pescara,
        City.Bari,
        City.Palermo,
        City.Naples,
        City.Siena,
        City.Florence,
        City.SanMarino,
        City.Verona,
        City.Genoa,
        City.Parma,
        City.Turin,
        City.Livorno,
        City.Lucca,
    ],
    [Country.Montenegro]: [
        City.Budva, 
        City.Podgorica, 
        City.Sutomore, 
        City.Bar, 
        City.DubrovnikM,
    ],
    [Country.NorthMacedonia]: [
        City.Skopje,
        City.Tetovo,
        City.Gostivar,
        City.Kichevo,
        City.Veles,
        City.Prilep,
        City.Bitola,
        City.Kumanovo,
        City.Shtip,
        City.Strumica,
    ],
    [Country.Poland]: [
        City.Warsaw, 
        City.Krakow, 
        City.Wroclav,
        City.Lodz,
        City.Poznan,
        City.Gdansk,
        City.Szczecin,
        City.Bydgoszcz,
        City.Lublin,
        City.Katowice,
        City.Gdynia,
        City.Czestochowa,
        City.Radom,
        City.Sosnowiec,
    ],
    [Country.Romania]: [
        City.Buharest,
    ],
    [Country.Serbia]: [
        City.Belgrad,
        City.NoviSad,
        City.Nish,
        City.Subotica,
        City.Kraguevac,
        City.Kralevo,
        City.Vranje,
        City.Zrenyanin,
        City.Vrshats,
        City.SremskaMitrovica,
        City.Pozarevac,
        City.Sombor,
        City.Panchievo,
        City.Leskovats,
        City.Smederevo,
    ],
    [Country.Slovakia]: [
        City.Koshitse, 
        City.Bratislava, 
        City.BanskaBystrica, 
        City.Humenne, 
        City.Levoca, 
        City.Levice,
        City.Martin,
        City.Michalovce,
        City.Malacky,
        City.Nitra,
        City.NoveZamky,
        City.Poprad,
        City.Presov,
        City.Prievidza,
        City.Ruzomberok,
        City.Skalica,
        City.Trencin,
        City.Trnava,
        City.Zilina,
        City.Zvolen,
    ],
    [Country.Slovenia]: [
        City.Maribor,
        City.Ljublijana,
        City.Tsele,
        City.Kran,
        City.Velenye,
        City.Koper,
        City.NoveMesto,
        City.Ptuy,
        City.Trbovlje,
        City.Jesenice,
    ],
    [Country.Spain]: [
        City.Barcelona, 
        City.Madrid, 
        City.Valencia,
    ],
    [Country.Switzerland]: [
        City.Zurich, 
        City.Bern,
        City.Geneva,
        City.Basel,
        City.Lausanne,
        City.Winterthur,
        City.Lucerne,
        City.SaintGallen,
        City.Biel,
        City.Thun,
        City.Kenitz,
    ],
}

// Кто? Где? Куда? Откуда?
export const translateCountry = {
    ua: {
        [Country.Austria]: ["Австрія","Австрії","Австрію","Австрії"],
        [Country.Bulgaria]: ["Болгарія", "Болгарії","Болгарію","Болгарії"],
        [Country.Croatia]: ["Хорватія", "Хорватії","Хорватію","Хорватії"],
        [Country.Czech]: ["Чехія","Чехії","Чехію","Чехії"],
        [Country.France]: ["Франція","Франції","Францію","Франції"],
        [Country.Germany]: ["Німеччина","Німеччині","Німеччину","Німеччини"],
        [Country.Greece]: ["Греція","Греції","Грецію","Греції"],
        [Country.Hungary]: ["Угорщина","Угорщині","Угорщину","Угорщини"],
        [Country.Italy]: ["Італія","Італії","Італію","Італії"],
        [Country.Montenegro]: ["Чорногорія","Чорногорії","Чорногорію","Чорногорії"],
        [Country.NorthMacedonia]: ["Північна Македонія","Північній Македонії","Північну Македонію","Північної Македонії"],
        [Country.Poland]: ["Польща","Польщі","Польщу","Польщі"],
        [Country.Romania]: ["Румунія","Румунії","Румунію","Румунії"],
        [Country.Serbia]: ["Сербія","Сербії","Сербію","Сербії"],
        [Country.Slovakia]: ["Словаччина","Словаччині","Словаччину","Словаччини"],
        [Country.Slovenia]: ["Словенія","Словенії","Словенію","Словенії"],
        [Country.Spain]: ["Іспанія","Іспанії","Іспанію","Іспанії"],
        [Country.Switzerland]: ["Швейцарія","Швейцарії","Швейцарію","Швейцарії"],
    },
    ru: {
        [Country.Austria]: ["Австрия","Австрии","Австрию","Австрии"],
        [Country.Bulgaria]: ["Болгарія","Болгарии","Болгарию","Болгарии"],
        [Country.Croatia]: ["Хорватия","Хорватии","Хорватию","Хорватии"],
        [Country.Czech]: ["Чехия","Чехии","Чехию","Чехии"],
        [Country.France]: ["Франция","Франции","Францию","Франции"],
        [Country.Germany]: ["Германия","Германии","Германию","Германии"],
        [Country.Greece]: ["Греция","Греции","Грецию","Греции"],
        [Country.Hungary]: ["Венгрия","Венгрии","Венгрию","Венгрии"],
        [Country.Italy]: ["Италия","Италии","Италию","Италии"],
        [Country.Montenegro]: ["Черногория","Черногории","Черногорию","Черногории"],
        [Country.NorthMacedonia]: ["Северная Македония","Северной Македонии","Северную Македонию","Северной Македонии"],
        [Country.Poland]: ["Польша","Польши","Польшу","Польши"],
        [Country.Romania]: ["Румыния","Румынии","Румынию","Румынии"],
        [Country.Serbia]: ["Сербия","Сербии","Сербию","Сербии"],
        [Country.Slovakia]: ["Словакия","Словакии","Словакию","Словакии"],
        [Country.Slovenia]: ["Словения","Словении","Словению","Словении"],
        [Country.Spain]: ["Испания","Испании","Испанию","Испании"],
        [Country.Switzerland]: ["Швейцария","Швейцарии","Швейцарию","Швейцарии"],
    }, 
    en: {
        [Country.Austria]: ["Austria","Austria","Austria","Austria"],
        [Country.Bulgaria]: ["Bulgaria","Bulgaria","Bulgaria","Bulgaria"],
        [Country.Croatia]: ["Croatia","Croatia","Croatia","Croatia"],
        [Country.Czech]: ["Czech Republic","Czech Republic","Czech Republic","Czech Republic"],
        [Country.France]: ["France","France","France","France"],
        [Country.Germany]: ["Germany","Germany","Germany","Germany"],
        [Country.Greece]: ["Greece","Greece","Greece","Greece"],
        [Country.Hungary]: ["Hungary","Hungary","Hungary","Hungary"],
        [Country.Italy]: ["Italy","Italy","Italy","Italy"],
        [Country.Montenegro]: ["Montenegro","Montenegro","Montenegro","Montenegro"],
        [Country.NorthMacedonia]: ["North Macedonia","North Macedonia","North Macedonia","North Macedonia"],
        [Country.Poland]: ["Poland","Poland","Poland","Poland"],
        [Country.Romania]: ["Romania","Romania","Romania","Romania"],
        [Country.Serbia]: ["Serbia","Serbia","Serbia","Serbia"],
        [Country.Slovakia]: ["Slovakia","Slovakia","Slovakia","Slovakia"],
        [Country.Slovenia]: ["Slovenia","Slovenia","Slovenia","Slovenia"],
        [Country.Spain]: ["Spain","Spain","Spain","Spain"],
        [Country.Switzerland]: ["Switzerland","Switzerland","Switzerland","Switzerland"],
    },
    t(locale, country, element) {
        if (!this[locale]) {
            return 'country locale ' + locale + ' not found' 
        }

        if (!this[locale][country]) {
            return 'country ' + country + ' not found' 
        }

        if (!this[locale][country][element]) {
            return 'country ' + country + ', element ' + element + ' not found' 
        }

        return this[locale][country][element]
    }
}

// Кто? Где? Куда? Откуда?
export const translateCity = {
    ua: {
        // Austria,
        [City.Vienna]: ["Відень","Відні","Відень","Відня"],
        [City.Gratz]: ["Грац","Граці","Грац","Граца"],
        [City.Linz]: ["Лінц","Лінці","Лінц","Лінца"],
        [City.Salzburg]: ["Зальцбург","Зальцбурзі","Зальцбург","Зальцбурга"],
        [City.Innsbruck]: ["Інсбрук","Інсбруці","Інсбрук","Інсбрука"],
        [City.KragenfurtWertez]: ["Крагенфурт-на-Вертеці","Крагенфурті-на-Вертеці","Крагенфурт-на-Вертеці","Крагенфурта-на-Вертеці"],
        [City.SanktPeltin]: ["Санкт-Пельтін","Санкт-Пельтіні","Санкт-Пельтін","Санкт-Пельтіна"],
        [City.Bregenz]: ["Брегенц","Брегенці","Брегенц","Брегенца"],
        [City.Parndorf]: ["Парндорф","Парндорфі","Парндорф","Парндорфа"],

        // Bulgaria,
        [City.Burgas]: ["Бургас","Бургасі","Бургас","Бургаса"],
        [City.Sofia]: ["Софія","Софії","Софію","Софії"],
        [City.Varna]: ["Варна","Варні","Варну","Варни"],
        [City.Plovdiv]: ["Пловдів","Пловдіві","Пловдів","Пловдіва"],
        [City.Pleven]: ["Плевен","Плевені","Плевен","Плевена"],
        [City.Ruse]: ["Русе","Русе","Русе","Русе"],
        
        // Croatia,
        [City.Zagreb]: ["Загреб","Загребі","Загреб","Загреба"],
        [City.Split]: ["Спліт","Спліті","Спліт","Спліта"],
        [City.Rijeka]: ["Рієка","Рієці","Рієку","Рієки"],
        [City.Osijek]: ["Осієк","Осієку","Осієк","Осієка"],
        [City.Zadar]: ["Задар","Задарі","Задар","Задара"],
        [City.Karlovac]: ["Карловац","Карловаці","Карловац","Карловаца"],
        [City.Pula]: ["Пула","Пулі","Пулу","Пули"],
        [City.Sisak]: ["Сісак","Сісаку","Сісак","Сісака"],
        [City.Sibenik]: ["Шибеник","Шибенику","Шибеник","Шибеника"],
        [City.Varazdin]: ["Вараждин","Вараждині","Вараждин","Вараждина"],
        [City.Dubrovnik]: ["Дубровник","Дубровнику","Дубровник","Дубровника"],
        [City.Belovar]: ["Беловар","Беловарі","Беловар","Беловара"],
        [City.Porec]: ["Пореч","Поречі","Пореч","Пореча"],
        [City.Omis]: ["Оміш","Оміші","Оміш","Оміша"],
        [City.Makarska]: ["Макарска","Макарсці","Макарску","Макарскої"],
        [City.BaskaVoda]: ["Баска-Вода","Баска-Воді","Баска-Воду","Баска-Води"],
        [City.Makarska]: ["Макарска","Макарсці","Макарску","Макарскої"],
        [City.Rovinj]: ["Ровінь","Ровіні","Ровінь","Ровіня"],
        
        // Czech,
        [City.Brno]: ["Брно","Брно","Брно","Брно"],
        [City.Prague]: ["Прага","Празі","Прагу","Праги"],
        [City.Ostrava]: ["Острава","Остраві","Остраву","Острави"],
        [City.Plzen]: ["Пльзень","Пльзені","Пльзень","Пльзеня"],
        [City.Liberec]: ["Ліберець","Ліберці","Ліберець","Лібереця"],
        [City.Olomouc]: ["Оломоуц","Оломоуці","Оломоуц","Оломоуца"],
        [City.CeskeBudejovice]: ["Чеське-Будейовіце","Чеському-Будейовіце","Чеському-Будейовіце","Чеського-Будейовіце"],
        [City.HradecKralove]: ["Градець-Кралове","Градці-Кралове","Градець-Кралове","Градця-Кралове"],
        [City.UstiNadLabem]: ["Усти-над-Лабем","Усти-над-Лабем","Усти-над-Лабем","Усти-над-Лабем"],
        [City.Pardubice]: ["Пардубіце","Пардубіце","Пардубіце","Пардубіце"],
        [City.Zlin]: ["Злін","Зліні","Злін","Зліна"],
        [City.Kladno]: ["Кладно","Кладно","Кладно","Кладно"],
        [City.Opava]: ["Опава","Опаві","Опаву","Опави"],
        [City.Jihlava]: ["Йіглава","Йіглаві","Йіглаву","Йіглави"],
        [City.Teplice]: ["Тепліце","Тепліце","Тепліце","Тепліце"],
        [City.Chomutov]: ["Хомутов","Хомутові","Хомутов","Хомутова"],
        [City.KarlovyVary]: ["Карлові-Вари","Карлових-Варах","Карлові-Вари","Карлових-Вар"],
        
        // France,
        [City.Marceille]: ["Марсель","Марселі","Марсель","Марселя"],
        [City.Lyon]: ["Ліон","Ліоні","Ліон","Ліона"],
        [City.Nice]: ["Ніцца","Ніцці","Ніццу","Ніцци"],
        [City.Paris]: ["Париж","Парижі","Париж","Парижа"],
        [City.Toulouse]: ["Тулуза","Тулузі","Тулузу","Тулузи"],
        
        // Germany,
        [City.Berlin]: ["Берлін","Берліні","Берлін","Берліна"],
        [City.Munich]: ["Мюнхен","Мюнхені","Мюнхен","Мюнхена"],
        [City.Nurnberg]: ["Нюрнберг","Нюрнберзі","Нюрнберг","Нюрнберга"],
        [City.Gamburg]: ["Гамбург","Гамбурзі","Гамбург","Гамбурга"],
        [City.Keln]: ["Кельн","Кельні","Кельн","Кельна"],
        [City.Frankfurt]: ["Франкфурт","Франкфурті","Франкфурт","Франкфурта"],
        [City.Dusseldorf]: ["Дюссельдорф","Дюссельдорфі","Дюссельдорф","Дюссельдорфа"],
        [City.Leiptsig]: ["Лейпциг","Лейпцизі","Лейпциг","Лейпцига"],
        [City.Dortmund]: ["Дортмунд","Дортмунді","Дортмунд","Дортмунда"],
        [City.Essen]: ["Ессен","Ессені","Ессен","Ессена"],
        [City.Bremen]: ["Бремен","Бремені","Бремен","Бремена"],
        [City.Drezden]: ["Дрезден","Дрездені","Дрезден","Дрездена"],
        [City.Gannover]: ["Ганновер","Ганновері","Ганновер","Ганновера"],
        [City.Magdeburg]: ["Магдебург","Магдебурзі","Магдебург","Магдебурга"],
        [City.Rostok]: ["Росток","Ростоку","Росток","Ростока"],

        // Greece,
        [City.Athens]: ["Афіни","Афінах","Афіни","Афін"],
        [City.Santorini]: ["Санторіні","Санторіні","Санторіні","Санторіні"],
        [City.Mykonos]: ["Міконос","Міконосі","Міконос","Міконоса"],
        [City.Crete]: ["Крит","Криті","Крит","Крита"],
        [City.Rhodes]: ["Родос","Родосі","Родос","Родоса"],
        [City.Corfu]: ["Корфу","Корфу","Корфу","Корфу"],
        [City.Meteora]: ["Метеора","Метеорі","Метеору","Метеори"],
        [City.Delphi]: ["Дельфи","Дельфах","Дельфи","Дельф"],
        [City.Nafplion]: ["Нафпліон","Нафпліоні","Нафпліон","Нафпліона"],
        [City.Olympia]: ["Олімпія","Олімпії","Олімпію","Олімпії"],
        [City.Zakynthos]: ["Закінтос","Закінтосі","Закінтос","Закінтоса"],
        [City.Thessaloniki]: ["Салоніки","Салоніках","Салоніки","Салонік"],
        [City.Kavala]: ["Кавала","Кавалі","Кавалу","Кавали"],
        [City.Alexandroupolis]: ["Александрополіс","Александрополісі","Александрополіс","Александрополіса"],
        [City.Sarti]: ["Сарті","Сарті","Сарті","Сарті"],
        
        // Hungary,
        [City.Budapest]: ["Будапешт", "Будапешті", "Будапешт","Будапешта"],
        [City.Debretsen]: ["Дебрецен","Дебрецені","Дебрецен","Дебрецена"],
        [City.Seged]: ["Сегед","Сегеді","Сегед","Сегеда"],
        [City.Mishkolts]: ["Мішкольц","Мішкольці","Мішкольц","Мішкольця"],
        [City.Pech]: ["Печ","Печі","Печ","Печа"],
        [City.Dior]: ["Дьор","Дьорі","Дьор","Дьора"],
        [City.Kaposhvar]: ["Капошвар","Капошварі","Капошвар","Капошвара"],
        [City.Nyiredgaza]: ["Ніредгаза","Ніредгазі","Ніредгазу","Ніредгази"],
        [City.Kechkemet]: ["Кечкемет","Кечкеметі","Кечкемет","Кечкемета"],
        [City.Sekeshfegervar]: ["Секешфегервар","Секешфегерварі","Секешфегервар","Секешфегервара"],
        [City.Sombatgey]: ["Сомбатгей","Сомбатгейі","Сомбатгей","Сомбатгея"],
        [City.Solnok]: ["Сольнок","Сольнокі","Сольнок","Сольнока"],
        [City.Tatabanya]: ["Татабаня","Татабані","Татабаню","Татабані"],
        [City.Bekeshchaba]: ["Бекешчаба","Бекешчабі","Бекешчабу","Бекешчаби"],
        [City.Erd]: ["Ерд","Ерді","Ерд","Ерда"],
        [City.Veshprem]: ["Вешпрем","Вешпремі","Вешпрем","Вешпрема"],
        [City.Shopron]: ["Шопрон","Шопроні","Шопрон","Шопрона"],
        [City.Eger]: ["Егер","Егері","Егер","Егера"],
        
        // Italy,
        [City.Milan]: ["Мілан","Мілані","Мілан","Мілана"],
        [City.Roma]: ["Рим","Римі", "Рим","Рима"],
        [City.Venice]: ["Венеція","Венеції","Венецію","Венеції"],
        [City.Bologna]: ["Болонья","Болоньї","Болонью","Болоньї"],
        [City.Rimini]: ["Ріміні","Ріміні","Ріміні","Ріміні"],
        [City.Ravenna]: ["Равенна","Равенні","Равенну","Равенни"],
        [City.Pesaro]: ["Пезаро","Пезаро","Пезаро","Пезаро"],
        [City.Ancona]: ["Анкона","Анконі","Анкону","Анкони"],
        [City.Pescara]: ["Пескара","Пескарі","Пескару","Пескари"],
        [City.Bari]: ["Барі","Барі","Барі","Барі"],
        [City.Palermo]: ["Палермо","Палермо","Палермо","Палермо"],
        [City.Naples]: ["Неаполь","Неаполі","Неаполь","Неаполя"],
        [City.Siena]: ["Сієна","Сієні","Сієну","Сієни"],
        [City.Florence]: ["Флоренція","Флоренції","Флоренцію","Флоренції"],
        [City.SanMarino]: ["Сан-Марино","Сан-Марино","Сан-Марино","Сан-Марино"],
        [City.Verona]: ["Верона","Вероні","Верону","Верони"],
        [City.Genoa]: ["Генуя","Генуї","Геную","Генуї"],
        [City.Parma]: ["Парма","Пармі","Парму","Парми"],
        [City.Turin]: ["Турин","Турині","Турин","Турину"],
        [City.Livorno]: ["Ліворно","Ліворно","Ліворно","Ліворно"],
        [City.Lucca]: ["Лукка","Луцці","Лукку","Лукки"],

        // Montenegro,
        [City.Budva]: ["Будва","Будві","Будву","Будви"],
        [City.Podgorica]: ["Подгориця","Подгориці","Подгорицю","Подгориці"],
        [City.Sutomore]: ["Сутоморе","Сутоморе","Сутоморе","Сутоморе"],
        [City.Bar]: ["Бар","Барі","Бар","Бара"],
        [City.DubrovnikM]: ["Дубровник","Дубровнику","Дубровник","Дубровника"],

        // North Macedonia,
        [City.Skopje]: ["Скоп'є","Скоп'є","Скоп'є","Скоп'є"],
        [City.Tetovo]: ["Тетово","Тетово","Тетово","Тетово"],
        [City.Gostivar]: ["Гостивар","Гостиварі","Гостивар","Гостивара"],
        [City.Kichevo]: ["Кичево","Кичево","Кичево","Кичево"],
        [City.Veles]: ["Велес","Велесі","Велес","Велеса"],
        [City.Prilep]: ["Прилеп","Прилепі","Прилеп","Прилепа"],
        [City.Bitola]: ["Бітола","Бітолі","Бітолу","Бітоли"],
        [City.Kumanovo]: ["Куманово","Куманово","Куманово","Куманово"],
        [City.Shtip]: ["Штип","Штипі","Штип","Штипа"],
        [City.Strumica]: ["Струмиця","Струмиці","Струмицю","Струмиці"],
        
        // Poland,
        [City.Krakow]: ["Краків","Кракові","Краків","Кракова"],
        [City.Warsaw]: ["Варшава","Варшаві","Варшаву","Варшави"],
        [City.Wroclav]: ["Вроцлав","Вроцлаві","Вроцлав","Вроцлава"],
        [City.Lodz]: ["Лодзь","Лодзі","Лодзь","Лодзя"],
        [City.Poznan]: ["Познань","Познані","Познань","Познаня"],
        [City.Gdansk]: ["Гданськ","Гданську","Гданськ","Гданська"],
        [City.Szczecin]: ["Щецин","Щецині","Щецин","Щецина"],
        [City.Bydgoszcz]: ["Бидгощ","Бидгощі","Бидгощ","Бидгоща"],
        [City.Lublin]: ["Люблін","Любліні","Люблін","Любліна"],
        [City.Katowice]: ["Катовіце","Катовіці","Катовіце","Катовіц"],
        [City.Gdynia]: ["Гданя","Гдані","Гданю","Гдані"],
        [City.Czestochowa]: ["Ченстохова","Ченстохові","Ченстохову","Ченстохови"],
        [City.Radom]: ["Радом","Радомі","Радом","Радома"],
        [City.Sosnowiec]: ["Сосновец","Сосновці","Сосновец","Сосновця"],
        
        // Romania,
        [City.Buharest]: ["Бухарест","Бухаресті","Бухарест","Бухареста"],

        // Serbia,
        [City.Belgrad]: ["Белград","Белграді","Белград","Белграда"],
        [City.NoviSad]: ["Нови-Сад","Нови-Саді","Нови-Сад","Нови-Сада"],
        [City.Nish]: ["Ниш","Ниші","Ниш","Ниша"],
        [City.Subotica]: ["Суботиця","Суботиці","Суботицю","Суботиці"],
        [City.Kraguevac]: ["Крагуєвач","Крагуєвачі","Крагуєвач","Крагуєвача"],
        [City.Kralevo]: ["Кралево","Кралево","Кралево","Кралево"],
        [City.Vranje]: ["Вранє","Вранє","Вранє","Вранє"],
        [City.Zrenyanin]: ["Зренянин","Зренянині","Зренянин","Зренянина"],
        [City.Vrshats]: ["Вршац","Вршаці","Вршац","Вршаца"],
        [City.SremskaMitrovica]: ["Сремська-Митровиця","Сремській-Митровиці","Сремську-Митровицю","Сремської-Митровиці"],   
        [City.Pozarevac]: ["Пожаревац","Пожареваці","Пожаревац","Пожареваца"],
        [City.Sombor]: ["Сомбор","Сомборі","Сомбор","Сомбора"],
        [City.Panchievo]: ["Панчево","Панчево","Панчево","Панчево"],
        [City.Leskovats]: ["Лесковац","Лесковаці","Лесковац","Лесковаца"],
        [City.Smederevo]: ["Смедерево","Смедерево","Смедерево","Смедерево"],
        
        // Slovakia,
        [City.Bratislava]: ["Братислава","Братиславі","Братиславу","Братислави"], 
        [City.Koshitse]: ["Кошице","Кошице","Кошице","Кошице"],
        [City.Nitra]: ["Нітра","Нітрі","Нітру","Нітри"],
        [City.Trnava]: ["Трнава","Трнаві","Трнаву","Трнави"],
        [City.BanskaBystrica]: ["Банська-бистриця","Банській-бистриці","Банську-бистрицю", "Банської-бистриці"],
        [City.Humenne]: ["Гуменне","Гуменному","Гуменне","Гуменного"],
        [City.Levoca]: ["Левоча","Левочі","Левочу","Левочі"],
        [City.Levice]: ["Левіце","Левіце","Левіце","Левіце"],
        [City.Martin]: ["Мартін","Мартіні","Мартін","Мартіна"],
        [City.Michalovce]: ["Михаловце","Михаловце","Михаловце","Михаловце"],
        [City.Malacky]: ["Малацки","Малацки","Малацки","Малацки"],
        [City.NoveZamky]: ["Нове-Замки","Нове-Замки","Нове-Замки","Нове-Замки"],
        [City.Poprad]: ["Попрад","Попраді","Попрад","Попрада"],
        [City.Presov]: ["Прешов","Прешові","Прешов","Прешова"],
        [City.Prievidza]: ["Прієвідза","Прієвідзі","Прієвідзу","Прієвідзи"],
        [City.Ruzomberok]: ["Ружомберок","Ружомбероку","Ружомберок","Ружомберока"],
        [City.Skalica]: ["Скаліца","Скаліці","Скаліцу","Скаліці"],
        [City.Trencin]: ["Тренчин","Тренчині","Тренчин","Тренчина"],
        [City.Zilina]: ["Жиліна","Жиліні","Жиліну","Жиліни"],
        [City.Zvolen]: ["Зволен","Зволені","Зволен","Зволена"],
        
        // Slovenia,
        [City.Maribor]: ["Марібор","Маріборі","Марібор","Марібора"],
        [City.Ljublijana]: ["Любляна","Любляні","Любляну","Любляни"],
        [City.Tsele]: ["Целє","Целє","Целє","Целє"],
        [City.Kran]: ["Крань","Крані","Крань","Крані"],
        [City.Velenye]: ["Веленьє","Веленьє","Веленьє","Веленьє"],
        [City.Koper]: ["Копер","Копері","Копер","Копера"],
        [City.NoveMesto]: ["Ново-Место","Ново-Место","Ново-Место","Ново-Место"],
        [City.Ptuy]: ["Птуй","Птуй","Птуй","Птуй"],
        [City.Trbovlje]: ["Трбовлє","Трбовлє","Трбовлє","Трбовлє"],
        [City.Jesenice]: ["Єсеніце","Єсеніце","Єсеніце","Єсеніце"],
        
        // Spain,
        [City.Barcelona]: ["Барселона","Барселоні","Барселону","Барселони"],
        [City.Madrid]: ["Мадрид","Мадриді","Мадрид","Мадрида"],
        [City.Valencia]: ["Валенсія","Валенсії","Валенсію","Валенсії"],
        
        // Switzerland,
        [City.Bern]: ["Берн","Берні","Берн","Берна"],  
        [City.Zurich]: ["Цюрих","Цюриху","Цюрих","Цюриха"],
        [City.Geneva]: ["Женева","Женеві","Женеву","Женеви"],
        [City.Basel]: ["Базель","Базелі","Базель","Базеля"],
        [City.Lausanne]: ["Лозанна","Лозанні","Лозанну","Лозанни"],
        [City.Winterthur]: ["Вінтертур","Вінтертурі","Вінтертур","Вінтертура"],
        [City.Lucerne]: ["Люцерн","Люцерні","Люцерн","Люцерна"],
        [City.SaintGallen]: ["Санкт-Галлен","Санкт-Галлені","Санкт-Галлен","Санкт-Галлена"],
        [City.Biel]: ["Біель","Біелі","Біель","Біеля"],
        [City.Thun]: ["Тун","Туні","Тун","Туна"],
        [City.Kenitz]: ["Кеніц","Кеніці","Кеніц","Кеніца"],
    },
    ru: {
        // Austria,
        [City.Vienna]: ["Вена","Вене","Вену","Вены"],
        [City.Gratz]: ["Грац","Граце","Грац","Граца"],
        [City.Linz]: ["Линц","Линце","Линц","Линца"],
        [City.Salzburg]: ["Зальцбург","Зальцбурге","Зальцбург","Зальцбурга"],
        [City.Innsbruck]: ["Инсбрук","Инсбруке","Инсбрук","Инсбрука"],
        [City.KragenfurtWertez]: ["Крагенфурт-на-Вертеце","Крагенфурте-на-Вертеце","Крагенфурт-на-Вертеце","Крагенфурта-на-Вертеце"],
        [City.SanktPeltin]: ["Санкт-Пельтин","Санкт-Пельтине","Санкт-Пельтин","Санкт-Пельтина"],
        [City.Bregenz]: ["Брегенц","Брегенце","Брегенц","Брегенца"],
        [City.Parndorf]: ["Парндорф", "Парндорфе", "Парндорф", "Парндорфа"],
        
        // Bulgaria,
        [City.Burgas]: ["Бургас","Бургасе","Бургасе","Бургаса"],
        [City.Sofia]: ["София","Софии","Софию","Софии"],
        [City.Varna]: ["Варна","Варне","Варну","Варны"],
        [City.Plovdiv]: ["Пловдив","Пловдиве","Пловдив","Пловдива"],
        [City.Pleven]: ["Плевен","Плевене","Плевен","Плевена"],
        [City.Ruse]: ["Русе","Русе","Русе","Русе"],
        
        // Croatia,
        [City.Zagreb]: ["Загреб","Загребе","Загреб","Загреба"],
        [City.Split]: ["Сплит","Сплите","Сплит","Сплита"],
        [City.Rijeka]: ["Риека","Риеке","Риеку","Риеки"],
        [City.Osijek]: ["Осиек","Осиеке","Осиек","Осиека"],
        [City.Zadar]: ["Задар","Задаре","Задар","Задара"],
        [City.Karlovac]: ["Карловац","Карловаце","Карловац","Карловаца"],
        [City.Pula]: ["Пула","Пуле","Пулу","Пулы"],
        [City.Sisak]: ["Сисак","Сисаке","Сисак","Сисака"],
        [City.Sibenik]: ["Шибеник","Шибенике","Шибеник","Шибеника"],
        [City.Varazdin]: ["Вараждин","Вараждине","Вараждин","Вараждина"],
        [City.Dubrovnik]: ["Дубровник","Дубровнике","Дубровник","Дубровника"],
        [City.Belovar]: ["Беловар","Беловаре","Беловар","Беловара"],
        [City.Porec]: ["Пореч","Порече","Пореч","Пореча"],
        [City.Omis]: ["Омиш","Омише","Омиш","Омиша"],
        [City.Makarska]: ["Макарска","Макарске","Макарску","Макарски"],
        [City.BaskaVoda]: ["Баска-Вода","Баска-Воде","Баска-Воду","Баска-Воды"],
        [City.Makarska]: ["Макарска","Макарске","Макарску","Макарски"],
        [City.Rovinj]: ["Ровинь","Ровине","Ровинь","Ровина"],
        
        // Czech,
        [City.Brno]: ["Брно","Брно","Брно","Брно"],
        [City.Prague]: ["Прага","Праге","Прагу","Праги"],
        [City.Ostrava]: ["Острава","Остраве","Остраву","Остравы"],
        [City.Plzen]: ["Пльзень","Пльзени","Пльзень","Пльзня"],
        [City.Liberec]: ["Либерец","Либерце","Либерец","Либерца"],
        [City.Olomouc]: ["Оломоуц","Оломоуце","Оломоуц","Оломоуца"],
        [City.CeskeBudejovice]: ["Ческе-Будейовице","Ческе-Будейовице","Ческе-Будейовице","Ческе-Будейовице"],
        [City.HradecKralove]: ["Градец-Кралове","Градце-Кралове","Градец-Кралове","Градца-Кралове"],
        [City.UstiNadLabem]: ["Усти-над-Лабем","Усти-над-Лабем","Усти-над-Лабем","Усти-над-Лабем"],
        [City.Pardubice]: ["Пардубице","Пардубице","Пардубице","Пардубице"],
        [City.Zlin]: ["Злин","Злине","Злин","Злина"],
        [City.Kladno]: ["Кладно","Кладно","Кладно","Кладно"],
        [City.Opava]: ["Опава","Опаве","Опаву","Опавы"],
        [City.Jihlava]: ["Йихлава","Йихлаве","Йихлаву","Йихлавы"],
        [City.Teplice]: ["Теплице","Теплице","Теплице","Теплице"],
        [City.Chomutov]: ["Хомутов","Хомутове","Хомутов","Хомутова"],
        [City.KarlovyVary]: ["Карловы-Вары","Карловых-Варах","Карловы-Вары","Карловых-Вар"],
        
        // France,
        [City.Marceille]: ["Марсель","Марселе","Марсель","Марселя"],
        [City.Lyon]: ["Лион","Лионе","Лион","Лиона"],
        [City.Nice]: ["Ницца","Ницце","Ниццу","Ниццы"],
        [City.Paris]: ["Париж","Париже","Париж","Парижа"],
        [City.Toulouse]: ["Тулуза","Тулузе","Тулузу","Тулузы"],
        
        // Germany,
        [City.Berlin]: ["Берлин","Берлине","Берлин","Берлина"],
        [City.Munich]: ["Мюнхен","Мюнхене","Мюнхен","Мюнхена"],
        [City.Nurnberg]: ["Нюрнберг","Нюрнберге","Нюрнберг","Нюрнберга"],
        [City.Gamburg]: ["Гамбург","Гамбурге","Гамбург","Гамбурга"],
        [City.Keln]: ["Кельн","Кельне","Кельн","Кельна"],
        [City.Frankfurt]: ["Франкфурт","Франкфурте","Франкфурт","Франкфурта"],
        [City.Dusseldorf]: ["Дюссельдорф","Дюссельдорфе","Дюссельдорф","Дюссельдорфа"],
        [City.Leiptsig]: ["Лейпциг","Лейпциге","Лейпциг","Лейпцига"],
        [City.Dortmund]: ["Дортмунд","Дортмунде","Дортмунд","Дортмунда"],
        [City.Essen]: ["Эссен","Эссене","Эссен","Эссена"],
        [City.Bremen]: ["Бремен","Бремене","Бремен","Бремена"],
        [City.Drezden]: ["Дрезден","Дрездене","Дрезден","Дрездена"],
        [City.Gannover]: ["Ганновер","Ганновере","Ганновер","Ганновера"],
        [City.Magdeburg]: ["Магдебург","Магдебурге","Магдебург","Магдебурга"],
        [City.Rostok]: ["Росток","Ростоке","Росток","Ростока"],

        // Greece
        [City.Athens]: ["Афины","Афинах","Афины","Афин"],
        [City.Santorini]: ["Санторини","Санторини","Санторини","Санторини"],
        [City.Mykonos]: ["Миконос","Миконосе","Миконос","Миконоса"],
        [City.Crete]: ["Крит","Крити","Крит","Крита"],
        [City.Rhodes]: ["Родос","Родосе","Родос","Родоса"],
        [City.Corfu]: ["Корфу","Корфу","Корфу","Корфу"],
        [City.Meteora]: ["Метеора","Метеорі","Метеору","Метеори"],
        [City.Delphi]: ["Дельфы","Дельфах","Дельфы","Дельф"],
        [City.Nafplion]: ["Нафплион","Нафплионе","Нафплион","Нафплиона"],
        [City.Olympia]: ["Олимпия","Олимпии","Олимпию","Олимпии"],
        [City.Zakynthos]: ["Закинтос","Закинтосе","Закинтос","Закинтоса"],
        [City.Thessaloniki]: ["Салоники","Салониках","Салоники","Салоник"],
        [City.Kavala]: ["Кавала","Кавале","Кавалу","Кавали"],
        [City.Alexandroupolis]: ["Александруполис","Александруполисе","Александруполис","Александруполиса"],
        [City.Sarti]: ["Сарти","Сарти","Сарти","Сарти"],
        
        // Hungary,
        [City.Budapest]: ["Будапешт", "Будапеште", "Будапешт","Будапешта"],
        [City.Debretsen]: ["Дебрецен","Дебрецене","Дебрецен","Дебрецена"],
        [City.Seged]: ["Сегед","Сегеде","Сегед","Сегеда"],
        [City.Mishkolts]: ["Мишкольц","Мишкольце","Мишкольц","Мишкольца"],
        [City.Pech]: ["Печ","Пече","Печ","Печа"],
        [City.Dior]: ["Дьор","Дьоре","Дьор","Дьора"],
        [City.Kaposhvar]: ["Капошвар","Капошваре","Капошвар","Капошвара"],
        [City.Nyiredgaza]: ["Ниредгаза","Ниредгазе","Ниредгазу","Ниредгазы"],
        [City.Kechkemet]: ["Кечкемет","Кечкемете","Кечкемет","Кечкемета"],
        [City.Sekeshfegervar]: ["Секешфегервар","Секешфегерваре","Секешфегервар","Секешфегервара"],
        [City.Sombatgey]: ["Сомбатгей","Сомбатгее","Сомбатгей","Сомбатгея"],
        [City.Solnok]: ["Сольнок","Сольноке","Сольнок","Сольнока"],
        [City.Tatabanya]: ["Татабаня","Татабане","Татабаню","Татабани"],
        [City.Bekeshchaba]: ["Бекешчаба","Бекешчабе","Бекешчабу","Бекешчабы"],
        [City.Erd]: ["Эрд","Эрде","Эрд","Эрда"],
        [City.Veshprem]: ["Вешпрем","Вешпреме","Вешпрем","Вешпрема"],
        [City.Shopron]: ["Шопрон","Шопроне","Шопрон","Шопрона"],
        [City.Eger]: ["Эгер","Эгере","Эгер","Эгера"],
        
        // Italy,
        [City.Milan]: ["Милан","Милане","Милан","Милана"],
        [City.Roma]: ["Рим","Риме", "Рим","Рима"],
        [City.Venice]: ["Венеция","Венеции","Венецию","Венеции"],
        [City.Bologna]: ["Болонья","Болоньи","Болонью","Болоньи"],
        [City.Rimini]: ["Римини","Римини","Римини","Римини"],
        [City.Ravenna]: ["Равенна","Равенни","Равенну","Равенни"],
        [City.Pesaro]: ["Пезаро","Пезаро","Пезаро","Пезаро"],
        [City.Ancona]: ["Анкона","Анконе","Анкону","Анконы"],
        [City.Pescara]: ["Пескара","Пескари","Пескару","Пескари"],
        [City.Bari]: ["Бари","Бари","Бари","Бари"],
        [City.Palermo]: ["Палермо","Палермо","Палермо","Палермо"],
        [City.Naples]: ["Неаполь","Неаполе","Неаполь","Неаполя"],
        [City.Siena]: ["Сиена","Сиене","Сиену","Сиены"],
        [City.Florence]: ["Флоренция","Флоренции","Флоренцию","Флоренции"],
        [City.SanMarino]: ["Сан-Марино","Сан-Марино","Сан-Марино","Сан-Марино"],
        [City.Verona]: ["Верона","Вероне","Верону","Верони"],
        [City.Genoa]: ["Генуя","Генуе","Геную","Генуи"],
        [City.Parma]: ["Парма","Парме","Парму","Пармы"],
        [City.Turin]: ["Турин","Турине","Турин","Турина"],
        [City.Livorno]: ["Ливорно","Ливорно","Ливорно","Ливорно"],
        [City.Lucca]: ["Лукка","Лукке","Лукку","Лукки"],

        // Montenegro,
        [City.Budva]: ["Будва","Будве","Будву","Будвы"],
        [City.Podgorica]: ["Подгорица","Подгорице","Подгорицу","Подгорицы"],
        [City.Sutomore]: ["Сутоморе","Сутоморе","Сутоморе","Сутоморе"],
        [City.Bar]: ["Бар","Баре","Бар","Бара"],
        [City.DubrovnikM]: ["Дубровник","Дубровнике","Дубровник","Дубровника"],

        // North Macedonia,
        [City.Skopje]: ["Скопье","Скопье","Скопье","Скопье"],
        [City.Tetovo]: ["Тетово","Тетово","Тетово","Тетово"],
        [City.Gostivar]: ["Гостивар","Гостиваре","Гостивар","Гостивара"],
        [City.Kichevo]: ["Кичево","Кичево","Кичево","Кичево"],
        [City.Veles]: ["Велес","Велесе","Велес","Велеса"],
        [City.Prilep]: ["Преп","Препе","Преп","Препа"],
        [City.Bitola]: ["Битола","Битоле","Битолу","Битолы"],
        [City.Kumanovo]: ["Куманово","Куманово","Куманово","Куманово"],
        [City.Shtip]: ["Штип","Штипе","Штип","Штипа"],
        [City.Strumica]: ["Струмица","Струмице","Струмицу","Струмицы"],
        
        // Poland,
        [City.Krakow]: ["Краков","Кракове","Краков","Кракова"],
        [City.Warsaw]: ["Варшава","Варшаве","Варшаву","Варшавы"],
        [City.Wroclav]: ["Вроцлав","Вроцлаве","Вроцлав","Вроцлава"],
        [City.Lodz]: ["Лодзь","Лодзи","Лодзь","Лодзи"],
        [City.Poznan]: ["Познань","Познани","Познань","Познани"],
        [City.Gdansk]: ["Гданск","Гданске","Гданск","Гданска"],
        [City.Szczecin]: ["Щецин","Щецине","Щецин","Щецина"],
        [City.Bydgoszcz]: ["Быдгощ","Быдгоще","Быдгощ","Быдгоща"],
        [City.Lublin]: ["Люблин","Люблине","Люблин","Люблина"],
        [City.Katowice]: ["Катовице","Катовице","Катовице","Катовице"],
        [City.Gdynia]: ["Гдыня","Гдыне","Гдыню","Гдыни"],
        [City.Czestochowa]: ["Ченстохова","Ченстохове","Ченстохову","Ченстоховы"],
        [City.Radom]: ["Радом","Радоме","Радом","Радома"],
        [City.Sosnowiec]: ["Сосновец","Сосновце","Сосновец","Сосновца"],

        // Romania,
        [City.Buharest]: ["Бухарест","Бухаресте","Бухарест","Бухареста"],

        // Serbia,
        [City.Belgrad]: ["Белград","Белграде","Белград","Белграда"],
        [City.NoviSad]: ["Нови-Сад","Нови-Саде","Нови-Сад","Нови-Сада"],
        [City.Nish]: ["Ниш","Нише","Ниш","Ниша"],
        [City.Subotica]: ["Суботица","Суботице","Суботицу","Суботицы"],
        [City.Kraguevac]: ["Крагуевац","Крагуеваце","Крагуевац","Крагуеваца"],
        [City.Kralevo]: ["Кралево","Кралево","Кралево","Кралево"],
        [City.Vranje]: ["Вране","Вране","Вране","Вране"],
        [City.Zrenyanin]: ["Зренянин","Зренянине","Зренянин","Зренянина"],
        [City.Vrshats]: ["Вршац","Вршаце","Вршац","Вршаца"],
        [City.SremskaMitrovica]: ["Сремска-Митровица","Сремска-Митровице","Сремска-Митровицу","Сремска-Митровицы"],
        [City.Pozarevac]: ["Пожаревац","Пожаревце","Пожаревац","Пожаревца"],
        [City.Sombor]: ["Сомбор","Сомборе","Сомбор","Сомбора"],
        [City.Panchievo]: ["Панчево","Панчево","Панчево","Панчево"],
        [City.Leskovats]: ["Лесковац","Лесковаце","Лесковац","Лесковаца"],
        [City.Smederevo]: ["Смедерево","Смедерево","Смедерево","Смедерево"],
        
        // Slovakia,
        [City.Bratislava]: ["Братислава","Братиславе","Братиславу","Братиславы"],
        [City.Koshitse]: ["Кошице","Кошице","Кошице","Кошице"],
        [City.Nitra]: ["Нитра","Нитре","Нитру","Нитры"],
        [City.Trnava]: ["Трнава","Трнаве","Трнаву","Трнавы"],
        [City.BanskaBystrica]: ["Банска-бистрица","Банськой-бистрице","Банску-бистрицу", "Банской-бистрицы"],
        [City.Humenne]: ["Гуменное","Гуменном","Гуменное","Гуменного"],
        [City.Levoca]: ["Левоча","Левоче","Левочу","Левочи"],
        [City.Levice]: ["Левице","Левице","Левице","Левице"],
        [City.Martin]: ["Мартин","Мартине","Мартин","Мартина"],
        [City.Michalovce]: ["Михаловце","Михаловце","Михаловце","Михаловце"],
        [City.Malacky]: ["Малацки","Малацки","Малацки","Малацки"],
        [City.NoveZamky]: ["Нове-Замки","Нове-Замки","Нове-Замки","Нове-Замки"],
        [City.Poprad]: ["Попрад","Попраде","Попрад","Попрада"],
        [City.Presov]: ["Прешов","Прешове","Прешов","Прешова"],
        [City.Prievidza]: ["Приевидза","Приевидзе","Приевидзу","Приєвидзы"],
        [City.Ruzomberok]: ["Ружомберок","Ружомбероке","Ружомберок","Ружомберока"],
        [City.Skalica]: ["Скалица","Скалице","Скалицу","Скалици"],
        [City.Trencin]: ["Тренчин","Тренчине","Тренчин","Тренчина"],
        [City.Zilina]: ["Жилина","Жилине","Жилину","Жилини"],
        [City.Zvolen]: ["Зволен","Зволене","Зволен","Зволена"],
        
        // Slovenia,
        [City.Maribor]: ["Марибор","Мариборе","Марибор","Марибора"],
        [City.Ljublijana]: ["Любляна","Любляне","Любляну","Любляны"],
        [City.Tsele]: ["Целе","Целе","Целе","Целе"],
        [City.Kran]: ["Крань","Крани","Крань","Крани"],
        [City.Velenye]: ["Веленье","Веленье","Веленье","Веленье"],
        [City.Koper]: ["Копер","Копере","Копер","Копера"],
        [City.NoveMesto]: ["Ново-Место","Ново-Месте","Ново-Место","Ново-Места"],
        [City.Ptuy]: ["Птуй","Птуй","Птуй","Птуй"],
        [City.Trbovlje]: ["Трбовле","Трбовле","Трбовле","Трбовле"],
        [City.Jesenice]: ["Есенице","Есенице","Есенице","Есенице"],
        
        // Spain,
        [City.Barcelona]: ["Барселона","Барселоне","Барселону","Барселоны"],
        [City.Madrid]: ["Мадрид","Мадриде","Мадрид","Мадрида"],
        [City.Valencia]: ["Валенсия","Валенсии","Валенсию","Валенсии"],
        
        // Switzerland,
        [City.Bern]: ["Берн","Берне","Берн","Берна"],
        [City.Zurich]: ["Цюрих","Цюрихе","Цюрих","Цюриха"],
        [City.Geneva]: ["Женева","Женеве","Женеву","Женевы"],
        [City.Basel]: ["Базель","Базеле","Базель","Базеля"],
        [City.Lausanne]: ["Лозанна","Лозанне","Лозанну","Лозанны"],
        [City.Winterthur]: ["Винтертур","Винтертуре","Винтертур","Винтертура"],
        [City.Lucerne]: ["Люцерн","Люцерне","Люцерн","Люцерна"],
        [City.SaintGallen]: ["Санкт-Галлен","Санкт-Галлене","Санкт-Галлен","Санкт-Галлена"],
        [City.Biel]: ["Биль","Биле","Биль","Биля"],
        [City.Thun]: ["Тун","Туне","Тун","Туна"],
        [City.Kenitz]: ["Кениц","Кенице","Кениц","Кеница"],
    },
    en: {
        // Austria,
        [City.Vienna]: ["Vienna","Vienna","Vienna","Vienna"],
        [City.Gratz]: ["Gratz","Gratz","Gratz","Gratz"],
        [City.Linz]: ["Linz","Linz","Linz","Linz"],
        [City.Salzburg]: ["Salzburg","Salzburg","Salzburg","Salzburg"],
        [City.Innsbruck]: ["Innsbruck","Innsbruck","Innsbruck","Innsbruck"],
        [City.KragenfurtWertez]: ["Klagenfurt","Klagenfurt","Klagenfurt","Klagenfurt"],
        [City.SanktPeltin]: ["Sankt-Peltin","Sankt-Peltin","Sankt-Peltin","Sankt-Peltin"], 
        [City.Bregenz]: ["Bregenz","Bregenz","Bregenz","Bregenz"],
        [City.Parndorf]: ["Parndorf","Parndorf","Parndorf","Parndorf"],
        
        // Bulgaria,
        [City.Burgas]: ["Burgas","Burgas","Burgas","Burgas"],
        [City.Sofia]: ["Sofia","Sofia","Sofia","Sofia"],
        [City.Varna]: ["Varna","Varna","Varna","Varna"],
        [City.Plovdiv]: ["Plovdiv","Plovdiv","Plovdiv","Plovdiv"],
        [City.Pleven]: ["Pleven","Pleven","Pleven","Pleven"],
        [City.Ruse]: ["Ruse","Ruse","Ruse","Ruse"],
        
        // Croatia,
        [City.Zagreb]: ["Zagreb","Zagreb","Zagreb","Zagreb"],
        [City.Split]: ["Split","Split","Split","Split"],
        [City.Rijeka]: ["Rijeka","Rijeka","Rijeka","Rijeka"],
        [City.Osijek]: ["Osijek","Osijek","Osijek","Osijek"],
        [City.Zadar]: ["Zadar","Zadar","Zadar","Zadar"],
        [City.Karlovac]: ["Karlovac","Karlovac","Karlovac","Karlovac"],
        [City.Pula]: ["Pula","Pula","Pula","Pula"],
        [City.Sisak]: ["Sisak","Sisak","Sisak","Sisak"],
        [City.Sibenik]: ["Sibenik","Sibenik","Sibenik","Sibenik"],
        [City.Varazdin]: ["Varazdin","Varazdin","Varazdin","Varazdin"],
        [City.Dubrovnik]: ["Dubrovnik","Dubrovnik","Dubrovnik","Dubrovnik"],
        [City.Belovar]: ["Belovar","Belovar","Belovar","Belovar"],
        [City.Porec]: ["Porec","Porec","Porec","Porec"],
        [City.Omis]: ["Omis","Omis","Omis","Omis"],
        [City.Makarska]: ["Makarska","Makarska","Makarska","Makarska"],
        [City.BaskaVoda]: ["Baska-Voda","Baska-Voda","Baska-Voda","Baska-Voda"],
        [City.Makarska]: ["Makarska","Makarska","Makarska","Makarska"],
        [City.Rovinj]: ["Rovinj","Rovinj","Rovinj","Rovinj"],
        
        // Czech,
        [City.Brno]: ["Brno","Brno","Brno","Brno"],
        [City.Prague]: ["Prague","Prague","Prague","Prague"],
        [City.Ostrava]: ["Ostrava","Ostrava","Ostrava","Ostrava"],
        [City.Plzen]: ["Plzen","Plzen","Plzen","Plzen"],
        [City.Liberec]: ["Liberec","Liberec","Liberec","Liberec"],
        [City.Olomouc]: ["Olomouc","Olomouc","Olomouc","Olomouc"],
        [City.CeskeBudejovice]: ["Ceske-Budejovice","Ceske-Budejovice","Ceske-Budejovice","Ceske-Budejovice"],
        [City.HradecKralove]: ["Hradec-Kralove","Hradec-Kralove","Hradec-Kralove","Hradec-Kralove"],
        [City.UstiNadLabem]: ["Usti-Nad-Labem","Usti-Nad-Labem","Usti-Nad-Labem","Usti-Nad-Labem"],
        [City.Pardubice]: ["Pardubice","Pardubice","Pardubice","Pardubice"],
        [City.Zlin]: ["Zlin","Zlin","Zlin","Zlin"],
        [City.Kladno]: ["Kladno","Kladno","Kladno","Kladno"],
        [City.Opava]: ["Opava","Opava","Opava","Opava"],
        [City.Jihlava]: ["Jihlava","Jihlava","Jihlava","Jihlava"],
        [City.Teplice]: ["Teplice","Teplice","Teplice","Teplice"],
        [City.Chomutov]: ["Chomutov","Chomutov","Chomutov","Chomutov"],
        [City.KarlovyVary]: ["Karlovy-Vary","Karlovy-Vary","Karlovy-Vary","Karlovy-Vary"],
        
        // France,
        [City.Marceille]: ["Marceille","Marceille","Marceille","Marceille"],
        [City.Lyon]: ["Lyon","Lyon","Lyon","Lyon"], 
        [City.Nice]: ["Nice","Nice","Nice","Nice"],
        [City.Paris]: ["Paris","Paris","Paris","Paris"],
        [City.Toulouse]: ["Toulouse","Toulouse","Toulouse","Toulouse"],
        
        // Germany,
        [City.Berlin]: ["Berlin","Berlin","Berlin","Berlin"],
        [City.Munich]: ["Munich","Munich","Munich","Munich"],
        [City.Nurnberg]: ["Nurnberg","Nurnberg","Nurnberg","Nurnberg"],
        [City.Gamburg]: ["Hamburg","Hamburg","Hamburg","Hamburg"],
        [City.Keln]: ["Cologne","Cologne","Cologne","Cologne"],
        [City.Frankfurt]: ["Frankfurt","Frankfurt","Frankfurt","Frankfurt"],
        [City.Dusseldorf]: ["Dusseldorf","Dusseldorf","Dusseldorf","Dusseldorf"],
        [City.Leiptsig]: ["Leipzig","Leipzig","Leipzig","Leipzig"],
        [City.Dortmund]: ["Dortmund","Dortmund","Dortmund","Dortmund"],
        [City.Essen]: ["Essen","Essen","Essen","Essen"],
        [City.Bremen]: ["Bremen","Bremen","Bremen","Bremen"],
        [City.Drezden]: ["Dresden","Dresden","Dresden","Dresden"],
        [City.Gannover]: ["Hannover","Hannover","Hannover","Hannover"],
        [City.Magdeburg]: ["Magdeburg","Magdeburg","Magdeburg","Magdeburg"],
        [City.Rostok]: ["Rostock","Rostock","Rostock","Rostock"],

        // Greece
        [City.Athens]: ["Athens","Athens","Athens","Athens"],
        [City.Santorini]: ["Santorini","Santorini","Santorini","Santorini"],
        [City.Mykonos]: ["Mykonos","Mykonos","Mykonos","Mykonos"],
        [City.Crete]: ["Crete","Crete","Crete","Crete"],
        [City.Rhodes]: ["Rhodes","Rhodes","Rhodes","Rhodes"],
        [City.Corfu]: ["Corfu","Corfu","Corfu","Corfu"],
        [City.Meteora]: ["Meteora","Meteora","Meteora","Meteora"],
        [City.Delphi]: ["Delphi","Delphi","Delphi","Delphi"],
        [City.Nafplion]: ["Nafplion","Nafplion","Nafplion","Nafplion"],
        [City.Olympia]: ["Olympia","Olympia","Olympia","Olympia"],
        [City.Zakynthos]: ["Zakynthos","Zakynthos","Zakynthos","Zakynthos"],
        [City.Thessaloniki]: ["Thessaloniki","Thessaloniki","Thessaloniki","Thessaloniki"],
        [City.Kavala]: ["Kavala","Kavala","Kavala","Kavala"],
        [City.Alexandroupolis]: ["Alexandroupolis","Alexandroupolis","Alexandroupolis","Alexandroupolis"],
        [City.Sarti]: ["Sarti","Sarti","Sarti","Sarti"],
        
        // Hungary,
        [City.Budapest]: ["Budapest", "Budapest", "Budapest","Budapest"],
        [City.Debretsen]: ["Debretsen","Debretsen","Debretsen","Debretsen"],
        [City.Seged]: ["Seged","Seged","Seged","Seged"],
        [City.Mishkolts]: ["Mishkolts","Mishkolts","Mishkolts","Mishkolts"],
        [City.Pech]: ["Pech","Pech","Pech","Pech"],
        [City.Dior]: ["Dior","Dior","Dior","Dior"],
        [City.Kaposhvar]: ["Kaposhvar","Kaposhvar","Kaposhvar","Kaposhvar"],
        [City.Nyiredgaza]: ["Nyiredgaza","Nyiredgaza","Nyiredgaza","Nyiredgaza"],
        [City.Kechkemet]: ["Kechkemet","Kechkemet","Kechkemet","Kechkemet"],
        [City.Sekeshfegervar]: ["Sekeshfegervar","Sekeshfegervar","Sekeshfegervar","Sekeshfegervar"],
        [City.Sombatgey]: ["Sombatgey","Sombatgey","Sombatgey","Sombatgey"],
        [City.Solnok]: ["Solnok","Solnok","Solnok","Solnok"],
        [City.Tatabanya]: ["Tatabanya","Tatabanya","Tatabanya","Tatabanya"],
        [City.Bekeshchaba]: ["Bekeshchaba","Bekeshchaba","Bekeshchaba","Bekeshchaba"],
        [City.Erd]: ["Erd","Erd","Erd","Erd"],
        [City.Veshprem]: ["Veshprem","Veshprem","Veshprem","Veshprem"],
        [City.Shopron]: ["Shopron","Shopron","Shopron","Shopron"],
        [City.Eger]: ["Eger","Eger","Eger","Eger"],
        
        // Italy,
        [City.Milan]: ["Milan","Milan","Milan","Milan"],
        [City.Roma]: ["Rome","Rome", "Rome","Rome"],
        [City.Venice]: ["Venice","Venice","Venice","Venice"],
        [City.Bologna]: ["Bologna","Bologna","Bologna","Bologna"],
        [City.Rimini]: ["Rimini","Rimini","Rimini","Rimini"],
        [City.Ravenna]: ["Ravenna","Ravenna","Ravenna","Ravenna"],
        [City.Pesaro]: ["Pesaro","Pesaro","Pesaro","Pesaro"],
        [City.Ancona]: ["Ancona","Ancona","Ancona","Ancona"],
        [City.Pescara]: ["Pescara","Pescara","Pescara","Pescara"],
        [City.Bari]: ["Bari","Bari","Bari","Bari"],
        [City.Palermo]: ["Palermo","Palermo","Palermo","Palermo"],
        [City.Naples]: ["Naples","Naples","Naples","Naples"],
        [City.Siena]: ["Siena","Siena","Siena","Siena"],
        [City.Florence]: ["Florence","Florence","Florence","Florence"],
        [City.SanMarino]: ["San-Marino","San-Marino","San-Marino","San-Marino"],
        [City.Verona]: ["Verona","Verona","Verona","Verona"],
        [City.Genoa]: ["Genoa","Genoa","Genoa","Genoa"],
        [City.Parma]: ["Parma","Parma","Parma","Parma"],
        [City.Turin]: ["Turin","Turin","Turin","Turin"],
        [City.Livorno]: ["Livorno","Livorno","Livorno","Livorno"],
        [City.Lucca]: ["Lucca","Lucca","Lucca","Lucca"],

        // Montenegro,
        [City.Budva]: ["Budva","Budva","Budva","Budva"],
        [City.Podgorica]: ["Podgorica","Podgorica","Podgorica","Podgorica"],
        [City.Sutomore]: ["Sutomore","Sutomore","Sutomore","Sutomore"],
        [City.Bar]: ["Bar","Bar","Bar","Bar"],
        [City.DubrovnikM]: ["Dubrovnik","Dubrovnik","Dubrovnik","Dubrovnik"],

        // North Macedonia,
        [City.Skopje]: ["Skopje","Skopje","Skopje","Skopje"],
        [City.Tetovo]: ["Tetovo","Tetovo","Tetovo","Tetovo"],
        [City.Gostivar]: ["Gostivar","Gostivar","Gostivar","Gostivar"],
        [City.Kichevo]: ["Kichevo","Kichevo","Kichevo","Kichevo"],
        [City.Veles]: ["Veles","Veles","Veles","Veles"],
        [City.Prilep]: ["Prilep","Prilep","Prilep","Prilep"],
        [City.Bitola]: ["Bitola","Bitola","Bitola","Bitola"],
        [City.Kumanovo]: ["Kumanovo","Kumanovo","Kumanovo","Kumanovo"],
        [City.Shtip]: ["Shtip","Shtip","Shtip","Shtip"],
        [City.Strumica]: ["Strumica","Strumica","Strumica","Strumica"],
        
        // Poland,
        [City.Krakow]: ["Krakow","Krakow","Krakow","Krakow"],
        [City.Warsaw]: ["Warsaw","Warsaw","Warsaw","Warsaw"],
        [City.Wroclav]: ["Wroclav","Wroclav","Wroclav","Wroclav"],
        [City.Lodz]: ["Lodz","Lodz","Lodz","Lodz"],
        [City.Poznan]: ["Poznan","Poznan","Poznan","Poznan"],
        [City.Gdansk]: ["Gdansk","Gdansk","Gdansk","Gdansk"],
        [City.Szczecin]: ["Szczecin","Szczecin","Szczecin","Szczecin"],
        [City.Bydgoszcz]: ["Bydgoszcz","Bydgoszcz","Bydgoszcz","Bydgoszcz"],
        [City.Lublin]: ["Lublin","Lublin","Lublin","Lublin"],
        [City.Katowice]: ["Katowice","Katowice","Katowice","Katowice"],
        [City.Gdynia]: ["Gdynia","Gdynia","Gdynia","Gdynia"],
        [City.Czestochowa]: ["Czestochowa","Czestochowa","Czestochowa","Czestochowa"],
        [City.Radom]: ["Radom","Radom","Radom","Radom"],
        [City.Sosnowiec]: ["Sosnowiec","Sosnowiec","Sosnowiec","Sosnowiec"],
        
        // Romania,
        [City.Buharest]: ["Buharest","Buharest","Buharest","Buharest"],

        // Serbia,
        [City.Belgrad]: ["Belgrad","Belgrad","Belgrad","Belgrad"],
        [City.NoviSad]: ["Novi-Sad","Novi-Sad","Novi-Sad","Novi-Sad"],
        [City.Nish]: ["Nish","Nish","Nish","Nish"],
        [City.Subotica]: ["Subotica","Subotica","Subotica","Subotica"],
        [City.Kraguevac]: ["Kraguevac","Kraguevac","Kraguevac","Kraguevac"],
        [City.Kralevo]: ["Kralevo","Kralevo","Kralevo","Kralevo"],
        [City.Vranje]: ["Vranje","Vranje","Vranje","Vranje"],
        [City.Zrenyanin]: ["Zrenyanin","Zrenyanin","Zrenyanin","Zrenyanin"],
        [City.Vrshats]: ["Vrsac","Vrsac","Vrsac","Vrsac"],
        [City.SremskaMitrovica]: ["Sremska-Mitrovica","Sremska-Mitrovica","Sremska-Mitrovica","Sremska-Mitrovica"],
        [City.Pozarevac]: ["Pozarevac","Pozarevac","Pozarevac","Pozarevac"],
        [City.Sombor]: ["Sombor","Sombor","Sombor","Sombor"],
        [City.Panchievo]: ["Panchievo","Panchievo","Panchievo","Panchievo"],
        [City.Leskovats]: ["Leskovats","Leskovats","Leskovats","Leskovats"],
        [City.Smederevo]: ["Smederevo","Smederevo","Smederevo","Smederevo"],
        
        // Slovakia,
        [City.Bratislava]: ["Bratislava","Bratislava","Bratislava","Bratislava"],
        [City.Koshitse]: ["Koshitse","Koshitse","Koshitse","Koshitse"],
        [City.Nitra]: ["Nitra","Nitra","Nitra","Nitra"],
        [City.Trnava]: ["Trnava","Trnava","Trnava","Trnava"],
        [City.BanskaBystrica]: ["Banska-Bystrica","Banska-Bystrica","Banska-Bystrica","Banska-Bystrica"],
        [City.Humenne]: ["Humenne","Humenne","Humenne","Humenne"],
        [City.Levoca]: ["Levoсa","Levoсa","Levoca","Levoca"],
        [City.Levice]: ["Levice","Levice","Levice","Levice"],
        [City.Martin]: ["Martin","Martin","Martin","Martin"],
        [City.Michalovce]: ["Michalovce","Michalovce","Michalovce","Michalovce"],
        [City.Malacky]: ["Malacky","Malacky","Malacky","Malacky"],
        [City.NoveZamky]: ["Nove-Zamky","Nove-Zamky","Nove-Zamky","Nove-Zamky"],
        [City.Poprad]: ["Poprad","Poprad","Poprad","Poprad"],
        [City.Presov]: ["Presov","Presov","Presov","Presov"],
        [City.Prievidza]: ["Prievidza","Prievidza","Prievidza","Prievidza"],
        [City.Ruzomberok]: ["Ruzomberok","Ruzomberok","Ruzomberok","Ruzomberok"],
        [City.Skalica]: ["Skalica","Skalica","Skalica","Skalica"],
        [City.Trencin]: ["Trencin","Trencin","Trencin","Trencin"],
        [City.Zilina]: ["Zilina","Zilina","Zilina","Zilina"],
        [City.Zvolen]: ["Zvolen","Zvolen","Zvolen","Zvolen"],
        
        // Slovenia,
        [City.Maribor]: ["Maribor","Maribor","Maribor","Maribor"],
        [City.Ljublijana]: ["Ljublijana","Ljublijana","Ljublijana","Ljublijana"],
        [City.Tsele]: ["Tsele","Tsele","Tsele","Tsele"],
        [City.Kran]: ["Kran","Kran","Kran","Kran"],
        [City.Velenye]: ["Velenye","Velenye","Velenye","Velenye"],
        [City.Koper]: ["Koper","Koper","Koper","Koper"],
        [City.NoveMesto]: ["Nove-Mesto","Nove-Mesto","Nove-Mesto","Nove-Mesto"],
        [City.Ptuy]: ["Ptuy","Ptuy","Ptuy","Ptuy"],
        [City.Trbovlje]: ["Trbovlje","Trbovlje","Trbovlje","Trbovlje"],
        [City.Jesenice]: ["Jesenice","Jesenice","Jesenice","Jesenice"],
        
        // Spain,
        [City.Barcelona]: ["Barcelona","Barcelona","Barcelona","Barcelona"],
        [City.Madrid]: ["Madrid","Madrid","Madrid","Madrid"],
        [City.Valencia]: ["Valencia","Valencia","Valencia","Valencia"],
        
        // Switzerland,
        [City.Bern]: ["Bern","Bern","Bern","Bern"],
        [City.Zurich]: ["Zurich","Zurich","Zurich","Zurich"],
        [City.Geneva]: ["Geneva","Geneva","Geneva","Geneva"],
        [City.Basel]: ["Basel","Basel","Basel","Basel"],
        [City.Lausanne]: ["Lausanne","Lausanne","Lausanne","Lausanne"],
        [City.Winterthur]: ["Winterthur","Winterthur","Winterthur","Winterthur"],
        [City.Lucerne]: ["Lucerne","Lucerne","Lucerne","Lucerne"],
        [City.SaintGallen]: ["Saint-Gallen","Saint-Gallen","Saint-Gallen","Saint-Gallen"],
        [City.Biel]: ["Biel","Biel","Biel","Biel"],
        [City.Thun]: ["Thun","Thun","Thun","Thun"],
        [City.Kenitz]: ["Kenitz","Kenitz","Kenitz","Kenitz"],
    },
    t(locale, city, element) {
        if (!this[locale]) {
            return 'city locale ' + locale + ' not found' 
        }

        if (!this[locale][city]) {
            return 'city ' + city + ' not found' 
        }

        if (!this[locale][city][element]) {
            return 'city ' + city + ', element ' + element + ' not found' 
        }

        return this[locale][city][element]
    }
}
